const name = [
  {id: 1, day: "T", number: 11},
  {id: 2, day: "F", number: 12},
  {id: 3, day: "S", number: 13},
  {id: 4, day: "S", number: 14},
  {id: 5, day: "M", number: 15},
  {id: 6, day: "T", number: 16},
  {id: 7, day: "W", number: 17},
  {id: 8, day: "T", number: 18},
  {id: 9, day: "F", number: 19},
  {id: 10, day: "S", number: 20},
  {id: 11, day: "S", number: 21},
  {id: 12, day: "M", number: 22},
  {id: 13, day: "T", number: 23},
  {id: 14, day: "W", number: 24},
  {id: 15, day: "T", number: 25},
  {id: 16, day: "F", number: 26},
  {id: 17, day: "S", number: 27},
  {id: 18, day: "S", number: 28},
  {id: 19, day: "M", number: 29},
  {id: 20, day: "T", number: 30},
  {id: 21, day: "W", number: 31},
  {id: 22, day: "T", number: 1},
  {id: 23, day: "F", number: 2},
  {id: 24, day: "S", number: 3},
  {id: 25, day: "S", number: 4},
  {id: 26, day: "M", number: 5},
  {id: 27, day: "T", number: 6},
  {id: 28, day: "W", number: 7},
  {id: 29, day: "T", number: 8},
  {id: 30, day: "F", number: 9},
  {id: 31, day: "S", number: 10},
];

export default name;
