const data = [
  {
    id: 1,
    name: "Finna A.",
    job: "UX designer",
    marginLeft: 12,
    width: 467,
    task: "slow swift transfer",
    dot: "#feab78",
    color: "#fff2ea",
    minColor: "#fd7e2e",
    minWidth: 68,

    img: "./images/list-img-04.png",
  },
  {
    id: 2,
    name: "Emma F.",
    job: "UI designer",
    marginLeft: 72,
    width: 600,
    minWidth: 32,
    task: "user profile",
    dot: "#fbdd5c",
    color: "#fef9e6",
    minColor: "#f9d018",
    img: "./images/list-img-02.png",
  },
  {
    id: 3,
    name: "Alex B.",
    job: "UX Analyst",
    marginLeft: 45,
    width: 500,
    minWidth: 77,
    dot: "#2e2c57",
    color: "#f5f4ff",
    minColor: "#090739",
    task: "slow swift transfer",
    img: "./images/list-img-03.png",
  },
  {
    id: 4,
    name: "Cody D.",
    job: "UX Analyst",
    marginLeft: 92,
    width: 475,
    minWidth: 41,

    task: "chat bot",
    dot: "#59dffd",
    color: "#e9f8fb",
    minColor: "#1bd3fc",
    img: "./images/list-img-01.png",
  },
  {
    id: 5,
    name: "Samanta G.",
    job: "UX designer",
    marginLeft: 12,
    width: 667,
    task: "slow swift transfer",

    minWidth: 68,
    dot: "#2e2c57",
    color: "#f5f4ff",
    minColor: "#090739",
    img: "./images/list-img-04.png",
  },
  {
    id: 6,
    name: "Erik F.",
    job: "UI designer",
    marginLeft: 72,
    width: 600,
    minWidth: 32,
    task: "user profile",
    dot: "#fbdd5c",
    color: "#fef9e6",
    minColor: "#f9d018",
    img: "./images/list-img-02.png",
  },
  {
    id: 7,
    name: "Anna S.",
    job: "UI designer",
    marginLeft: 45,
    width: 521,
    minWidth: 77,
    dot: "#59dffd",
    color: "#e9f8fb",
    minColor: "#1bd3fc",
    task: "slow swift transfer",
    img: "./images/list-img-03.png",
  },
  {
    id: 8,
    name: "Emma F.",
    job: "UI designer",
    marginLeft: 92,
    width: 425,
    minWidth: 41,

    task: "chat bot",
    dot: "#2e2c57",
    color: "#f5f4ff",
    minColor: "#090739",
    img: "./images/list-img-01.png",
  },

  {
    id: 9,
    name: "Finna A.",
    job: "UX designer",
    marginLeft: 45,
    width: 400,
    minWidth: 77,
    dot: "#fbdd5c",
    color: "#fef9e6",
    minColor: "#f9d018",
    task: "slow swift transfer",
    img: "./images/list-img-03.png",
  },
  {
    id: 10,
    name: "Emma F.",
    job: "UI designer",
    marginLeft: 92,
    width: 425,
    minWidth: 41,

    task: "chat bot",
    dot: "#feab78",
    color: "#fff2ea",
    minColor: "#fd7e2e",
    img: "./images/list-img-01.png",
  },
];
export default data;
